### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by lorrp1** [harveybc/gym-forex#1]
i have installed all, but it seems python does not recognize the folder gym_forex, any idea on how to fix it? 

Traceback (most recent call last):
  File "agents/agent_NEAT_reps_v3.py", line 7, in <module>
    import gym_forex
ImportError: No module named 'gym_forex'

**Comment by harveybc** [comment]
You have to export the PYTHONPATH variable, i updated the Readme.md. I hope you can use it with the new instructions. Sorry for the delay on the answer.
